### ISSUE TITLE
How can I pass body of a request to bugsnag?

### ISSUE THREAD

**Issue by saikat056** [bugsnag/bugsnag-go#100]
Recently I am trying to use Bugsnag in a go-project. I am able to send Bugsnag notification from my project. But, whenever I open up the error in Bugsnag, I can only see request URL and a header. I want to see to the body of the request as well. Otherwise, it's not helpful.

I understand this is not a proper place to ask a question. Can anyone please redirect me to the actual forum where I can post my question?

**Comment by kattrali** [comment]
Depending on which framework you are using, the original request is available to `bugsnag.OnBeforeNotify` callbacks in the `RawData` property of `bugsnag.Event`, which you can use to modify and append information to a crash report before it is delivered. More information here: https://docs.bugsnag.com/platforms/go/other/customizing-error-reports

> I understand this is not a proper place to ask a question. Can anyone please redirect me to the actual forum where I can post my question?

For usage queries like these and other feedback, feel free to send a message to support@bugsnag.com
