### ISSUE TITLE
Logger configuration

### ISSUE THREAD

**Issue by wolfeidau** [bugsnag/bugsnag-go#12]
It would be wonderful if you could accept just a function for logging rather than the entire logger.

As far as I can tell your only using one function anyway.

The reason I suggest making this change is Logger is a struct and can't be replaced with anything else, so if your using an alternate logger your out of luck.

In the long run a function will make it easier for you to test anyway.

I am happy to add this option as a pull request if your conducive to the change.

Cheers

**Comment by snmaynard** [comment]
This is in 1.0.3!

**Comment by wolfeidau** [comment]
Great, thanks for merging!
