### ISSUE TITLE
invalid API Key when calling Notify

### ISSUE THREAD

**Issue by bjm88** [bugsnag/bugsnag-go#120]
I'm setting up bugsnag in main, as well as autonotify in gin, but calling explicitly notify gives invalid api key error...
bugsnag/defaultReportPublisher.publishReport: bugsnag/payload.deliver: invalid api key: ''

	if len( os.Getenv("BUGSNAG_CLIENT_API_KEY")) > 0 {
			bugsnag.Configure(bugsnag.Configuration{
				APIKey:          os.Getenv("BUGSNAG_CLIENT_API_KEY"),
				ReleaseStage:    os.Getenv("CD_ENV"),
				ProjectPackages: []string{"main", "github.com/myapp"},
			})
		}

in our utils package....
func ReportError(err error, context string, msg string){
	if len(os.Getenv("BUGSNAG_CLIENT_API_KEY")) > 0 {
		bugsnag.Notify(err,
			bugsnag.MetaData{
				"Metadata":{
					"Context": context,
					"Msg": msg,
				}})
		}
}

our api key is clearly set in env variables....do we need to using Notify(err, ctx, data) I tried calling with nil ctx or just 2 params without ctx, was same behavior.  In a place I dont have context how to call?  Is that reason?

**Comment by bengourley** [comment]
Hi @bjm88. It sounds like you're calling `bugsnag.Notify(…)` before `bugsnag.Configure(…)` (or `bugsnaggin.AutoNotify(…)`).

You should call `bugsnag.Configure(…)` or `bugsnaggin.AutoNotify(…)` as soon as possible to ensure that bugsnag is configured and ready for the first time you manually call `Notify()`.

It's absolutely ok to use `Notify()` without the `ctx` param and that shouldn't have anything to do with the API key problem you're seeing.

If this doesn't solve your issue, please get in touch with us at support@bugsnag.com and we'll be happy to help figure it out.
