### ISSUE TITLE
Notify not working in Docker container

### ISSUE THREAD

**Issue by adamallred** [bugsnag/bugsnag-go#124]
### Expected behavior
Issuing a panic after configuring bugsnag in a docker image works.

### Observed behavior
```
$ docker run docker-build-test
2019/08/23 19:30:38 WARNING: Bugsnag notify endpoint configured without also configuring the sessions endpoint. No sessions will be recorded
$
# no panic is logged to bugsnag
```

### Steps to reproduce
Build a simple go program that tests sending unhandled panics. For example, in `cmd/main.go`:

```
package main

import "github.com/bugsnag/bugsnag-go"

func main() {
	bugsnag.Configure(bugsnag.Configuration{
		APIKey: "<key>",
	})

	panic("broke")
}
```

Build this program and run it via docker. In `Dockerfile`:

```
FROM golang:1.12-alpine
COPY . /src
RUN cd /src && go build -mod=vendor -o /usr/bin/test-bugsnag ./cmd/main.go

ENTRYPOINT ["/usr/bin/test-bugsnag" ]
```

```
$ docker build -t "bugsnag-go-test" --file=Dockerfile .
$ docker run "bugsnag-go-test"
```

### Version
Bugsnag: 1.5.3
Docker for Mac: 2.1.0.1
Go: 1.12-alpine (using the vendor mod)

### Additional information

This is weird. If you run the same command by hand, it works, e.g.

```
$ docker run -it --entrypoint /bin/sh bugsnag-go-test
/go # /usr/bin/test-bugsnag
2019/08/23 19:36:03 WARNING: Bugsnag notify endpoint configured without also configuring the sessions endpoint. No sessions will be recorded
2019/08/23 19:36:03 WARNING: Bugsnag notify endpoint configured without also configuring the sessions endpoint. No sessions will be recorded
panic: broke

goroutine 1 [running]:
main.main()
	/src/cmd/main.go:13 +0x79
/go # 2019/08/23 19:36:03 notifying bugsnag: broke

/go # exit
```

If you compile the binary and copy it into a mounted volume, then run it locally, it works.

I would *guess* this might be a local problem, or a docker problem, but I also uploaded the docker image to Google Could Run and tried to run it there, with the same non-working behavior. I guess Cloud Run cloud be Docker-based as well. I also tried the debian stretch-based golang image, with the same results. I also tested in docker in a Linux VM with the same results. Running the binary under `strace` actually works, so I'm assuming there's a race condition somewhere, but I can't manage to dig it out.

I also had a co-worker try on his laptop (using Docker for Mac), with the same observed behavior, so I don't think it's localized to me.

**Comment by mattdyoung** [comment]
Hi @adamallred 

Hopefully the guidance we gave on your related support thread has given you a way forward.

For the benefit of any other users of the library coming across this issue I'm repeating the guidance here too.

Unfortunately there isn't a way in the go language to always capture and report unhandled panics at the top level. We therefore use a panic handler that is started as a child process and captures any panic from you running process.

On most unix type systems, with an init process, that runs as PID1, if a parent process dies, the child is adopted by the init process.  Docker by default doesn't use an init process and runs your main process as PID 1.  When the main process ends the docker container shuts straight down. In the case of a panic, it doesn't provide the monitoring child process any time to report the crash.

You should be able to get this to work by using an approach with some sort of separate init process. This page suggests 3 such approaches for handling multiple processes in containers:
https://docs.docker.com/config/containers/multi-service_container/

Also, if your notifier is configured as async then the notifier caches and the reports are sent from a separate goroutine.  If your main process shuts down before the notifier goroutine has finished you won't get a report.  Changing to synchronous, should resolve this, but with the caveat that, if you are notifying from a goroutine, then the main process closing may also prevent notifications being sent:
https://docs.bugsnag.com/platforms/go/other/configuration-options/#synchronous

**Comment by mikeparker** [comment]
I'm seeing this too in AWS ECS Fargate, I noticed the program just quits with no logging or anything. I traced it to this line of code:

panicwrap/monitor.go
`err = dup2(int(write.Fd()), int(os.Stderr.Fd()))`

I'm still investigating what's going on but one of these calls is blowing up.
