### ISSUE TITLE
Add Go Modules support.

### ISSUE THREAD

**Issue by olegburov** [bugsnag/bugsnag-go#133]
### Expected behavior
Could you please add [Go Modules](https://blog.golang.org/using-go-modules) support? Must be released as `v2.x` version. Please see here for details https://blog.golang.org/v2-go-modules.

**Comment by steve-nester-uk** [comment]
@olegburov thanks for raising, we are going to look into this.

**Comment by xander-jones** [comment]
Hey @olegburov, Support for Go Modules has been added in https://github.com/bugsnag/bugsnag-go/releases/tag/v2.0.0

**Comment by olegburov** [comment]
@xander-jones thank you! I'm upgrading now.
