### ISSUE TITLE
Add example of keeping stack trace from error

### ISSUE THREAD

**Issue by mikeparker** [bugsnag/bugsnag-go#134]
### Problem
I've just spent a little time digging through the bugsnag code trying to figure out how to get error stack traces propogating properly.

It appears what we need to do is use `errors.New(err)` (using the bugsnag errors lib) to capture the stack trace at the time of error creation.

### Solution
Add docs or brief example of how to keep the stack trace.

### Version
Latest, 1.5.3

### Additional information
We are wrapping our program in an error catcher so there is only 1 `bugsnag.Notify` call in the program.

The stack traces at Notify time mean that every error stack trace looks the same, regardless of where it was thrown from the program.

The stack trace should be from the error.

### Errors objects

bugsnag-go includes the `errors` object which was, I believe, extracted out to here https://github.com/go-errors/errors but the current library doesn't seem to use `go-errors/errors`, despite the blog talking about it (https://www.bugsnag.com/blog/go-errors). The blog also doesnt say how to use `errors` object to ensure the stack trace is kept into the Notify call.

**Comment by johnkiely1** [comment]
Hi @mikeparker ,

Thanks for reporting this, we are looking into it.

**Comment by johnkiely1** [comment]
Hi @mikeparker 
An [updated example](https://docs.bugsnag.com/platforms/go/reporting-handled-errors/) has now been added to the documentation.

**Comment by mikeparker** [comment]
@johnkiely1 perfect! I haven't gone through and tested it for correctness everywhere but it looks great from a quick look, thanks!
