### ISSUE TITLE
Looking for SDK like rollbar's or sentry's

### ISSUE THREAD

**Issue by ORESoftware** [bugsnag/bugsnag-go#135]
I am looking for a Go SDK (and JS/TS SDK) for sending errors to our cloud account, like so:

https://github.com/getsentry/sentry-go

and

https://github.com/rollbar/rollbar-go

does bugsnag have an SDK like this? I don't want panic based middleware - I am looking to simply write messages to the cloud account and wait for those messages to all be sent before shutting down my go process

**Comment by ORESoftware** [comment]
looks like this does what I want:

https://docs.bugsnag.com/platforms/go/net-http/#reporting-handled-errors

?

**Comment by johnkiely1** [comment]
Hi @ORESoftware ,

Yes we have a supported integration for Go. 

Looks like you may have already found what you wanted. Yes you can manually notify Bugsnag of a handled error as required. 
 
You can find out more about our Go integration [here](https://www.bugsnag.com/platforms/go-lang-error-reporting) and from our [official documentation](https://docs.bugsnag.com/platforms/go/).
