### ISSUE TITLE
Skip stack frame

### ISSUE THREAD

**Issue by cenkalti** [bugsnag/bugsnag-go#15]
I am using a wrapper around Notify function that prepares some arguments to Notify function. This causes all errors to appear as same filename:lineno in Bugsnag dashboard. Can we add an option to skip a stack frame for using with Notify?

**Comment by ConradIrwin** [comment]
Hey @cenkalti,

You can do this using the `bugsnag-go/errors` package:

```go
import (
  "github.com/bugsnag/bugsnag-go"
  "github.com/bugsnag/bugsnag-go/errors"
)

func LogError(e error) {
    // Attach the stack-trace to the error, skipping one frame.
    e = errors.New(e, 1)
    bugsnag.Notify(e)
}
```

**Comment by cenkalti** [comment]
Thank you, thats great. You should document this feature.
