### ISSUE TITLE
Feature request: synchronous Notify()

### ISSUE THREAD

**Issue by dogweather** [bugsnag/bugsnag-go#168]
### Description

I have a codebase which checks for errors and exits immediately with `log.Fatalf()`. I haven't found a way to notify Bugsnag. `Notify()` uses a Goroutine internally and so I have no way to wait until it completes.

**Describe the solution you'd like**

I'd like a synchronous `Notify()` which gives the caller the ability to manage the concurrency. Then, I could ensure that the notification completes before exiting the program.

**Describe alternatives you've considered**

Starting some kind of notifier in a child process. Or digging into the bugsnag-go source to copy/paste `Notify()` with modifications.

**Comment by dogweather** [comment]
Ah hah, I found the `Synchronous` configuration option.

**Comment by xander-jones** [comment]
👋. For future travellers, this option config option can be found here: https://docs.bugsnag.com/platforms/go/other/configuration-options/#synchronous
