### ISSUE TITLE
panicwrap breaks Windows Service applications

### ISSUE THREAD

**Issue by iamacarpet** [bugsnag/bugsnag-go#177]
### Describe the bug

panicwrap's process forking, which appears to happen using an init() function, is causing Windows Service applications to fail to start.

This is because they check for the parent process executable name == "services.exe"

### Steps to reproduce
1. Start with the [windows service example](https://github.com/golang/sys/tree/master/windows/svc/example).
2. Add in bugsnag
3. Build & drop onto a Windows box
4. Run with "install" then "start" on the CLI and see the service fails to start.

### Environment
* Bugsnag Go version: latest
* Go version: 1.16.4
* Integration framework version:
   none

**Comment by mattdyoung** [comment]
Hi @iamacarpet 

Are you using v2.x of bugsnag-go? If you are using v1.x, there is an [upgrade guide](https://github.com/bugsnag/bugsnag-go/blob/v2.0.0/UPGRADING.md) and revised documentation:
https://docs.bugsnag.com/platforms/go/

In v2.x you can generally use [panic-monitor](https://github.com/bugsnag/panic-monitor) to report unhandled panics, which doesn't fork the process:
https://docs.bugsnag.com/platforms/go/other/#reporting-unhandled-panics

**Comment by mattdyoung** [comment]
Closing this for now but if this doesn't solve your issue then please provide further details and we can look into this further.
