### ISSUE TITLE
failure to build on aarch64

### ISSUE THREAD

**Issue by Cl00e9ment** [bugsnag/bugsnag-go#179]
Please bump panicwrap version to fix the issue. See https://github.com/bugsnag/panicwrap/issues/20
Thanks

**Comment by johnkiely1** [comment]
Hi @Cl00e9ment,
 
Could you confirm which version of bugsnag-go you are using?
Thanks

**Comment by Cl00e9ment** [comment]
I'm using the latest version (2.1.1) which uses panicwrap 1.3.2. The bug I'm refering to has been fixed in panicwrap 1.3.3 (see changelog https://github.com/bugsnag/panicwrap/releases/tag/v1.3.3), so it would be great if the panicwrap version was bumped to the latest one (1.3.4).

**Comment by johnkiely1** [comment]
Hi @Cl00e9ment,

Thanks for confirming, yes we will look to update date that as soo as priorities allow.

**Comment by xander-jones** [comment]
Hey @Cl00e9ment, bumped the `panicwrap` version to v1.3.4 in `bugsnag-go` v2.1.2. Thanks for raising this issue!
