### ISSUE TITLE
When a third part doesn't have APIKey

### ISSUE THREAD

**Issue by LuizFJP** [bugsnag/bugsnag-go#189]
I'm getting APIKey by environment variable. Untill there ok, but when a colleague doesn't have this key. They receive that:
2022/06/01 13:52:18 bugsnag/defaultReportPublisher.publishReport: bugsnag/payload.deliver: invalid api key: ''
2022/06/01 13:52:18 bugsnag/defaultReportPublisher.publishReport: bugsnag/payload.deliver: invalid api key: ''

We don't want to receive that message, what is the best recomendation?

**Comment by luke-belton** [comment]
Hi @LuizFJP - the Bugsnag API key is designed as a write-only key that cannot be used for read access to any of your data. If you wish to disable reporting in certain environments, you could consider using the [`NotifyReleaseStages` config option](https://docs.bugsnag.com/platforms/go/other/configuration-options/#notifyreleasestages).
