### ISSUE TITLE
needless "panicwrap" fork?

### ISSUE THREAD

**Issue by onlyjob** [bugsnag/bugsnag-go#29]
_bugsnag-go_ [depends](../blob/master/panicwrap.go#L7) on [github.com/bugsnag/panicwrap](http://github.com/bugsnag/panicwrap) which is a fork of [github.com/ConradIrwin/panicwrap](http://github.com/ConradIrwin/panicwrap) which is a fork of [github.com/mitchellh/panicwrap](http://github.com/mitchellh/panicwrap).
The latter appears to be best maintained and most up-to-date.

Needless forking is harmful.

Please consider using original _panicwrap_: https://github.com/mitchellh/panicwrap

**Comment by kattrali** [comment]
Thanks for the report, @onlyjob. The fork of panicwrap was not unintended, as it adds support for monitoring a process without interrupting signal handling. [There is an upstream issue and PR for supporting this](https://github.com/mitchellh/panicwrap/pull/2). Conrad no longer intended to support his fork, so this one exists in its place.

**Comment by onlyjob** [comment]
Thanks.

**Comment by konradreiche** [comment]
What are the advantages of using a fork over Go's recover mechanism?
