### ISSUE TITLE
Undocumented process fork when configuring bugsnag

### ISSUE THREAD

**Issue by lwc** [bugsnag/bugsnag-go#34]
Due to an undocumented "feature" of this library [seen here](https://github.com/bugsnag/bugsnag-go/blob/master/panicwrap.go#L10-L12). 

Looks like it forks the current process and attempts to trap any panics in the child process's output.

Pretty unexpected behaviour for a library, and to make matters worse, the documentation for it was recently deleted: https://github.com/bugsnag/bugsnag-go/commit/008a3ab73b84bd20f62003318d5709993cd957a6#diff-04c6e90faac2675aa89e2176d2eec7d8L398

This can cause all manner of strange behaviour in initialisation code that can introduce issues depending on when bugsnag is configured. For example, the parent process could hold database connections open, pollute runtime metrics sent to statsd or cause the behaviour described in https://github.com/bugsnag/bugsnag-go/issues/32.

Something as seemingly trivial as the order datadog and bugsnag are configured leads to this:
<img width="391" alt="screen shot 2016-06-14 at 11 50 01 am" src="https://cloud.githubusercontent.com/assets/336402/16030811/5a81b1a2-3238-11e6-984e-9921c0c7a421.png">

**Comment by kattrali** [comment]
Thank you for the report, @lwc. Bugsnag forks the current process to capture panics in the child process' output as its the only way that panic detection can work. 

The documentation was moved to a hosted site to make the readme simpler and clearer for getting started, and is available here for `net/http` apps (and other types of Go application guides are linked from the [platform integration page](http://docs.bugsnag.com/platforms/):

* [`PanicHandler` in Configuration options](http://docs.bugsnag.com/platforms/go/net-http/configuration-options/#panichandler)
* [Integration guide](http://docs.bugsnag.com/platforms/go/net-http/)

> Something as seemingly trivial as the order datadog and bugsnag are configured leads to this:

To be clear, does the memory allocation issue occur when Bugsnag is initialized before the rest of the program?

**Comment by Vektah** [comment]
> The documentation was moved to a hosted site to make the readme simpler and clearer for getting started

This might make the docs more readable, but the only way we tracked down the cause of this issue was:
```
grep -Ri fork vendor
```
And that wont show up any more. I'm very glad it was there in master.

This was after seeing some strange graphs like above, and a second copy of the binary running on the prod machines. Of course we don't configure bugsnag in dev, so this ghost binary only exists in prod and is completely untested in CI.

> To be clear, does the memory allocation issue occur when Bugsnag is initialized before the rest of the program?

The issue above was caused by our runtime logger starting before bugsnag, causing it to monitor both binaries at the same time.

What does the subprocess offer over:
```
func main() {
    bugsnag.Configure(bugsnag.Configuration{
        APIKey: "YOUR_API_KEY_HERE",
        ReleaseStage: "production",
        // more confipguration options
    })
    defer bugsnag.PanicHandler
```

**Comment by lwc** [comment]
> To be clear, does the memory allocation issue occur when Bugsnag is initialized before the rest of the program?

Once we realised Bugsnag was the cause and moved it's initialisation as early as possible, the memory allocation (and a host of other) issues went away - the point is that something as innocuous as the order one initialises libraries should not have such extreme side effects.

I would consider making this behaviour opt-in instead of opt-out - it's a fairly strong opinion about the nature of the app being augmented and in the context of web services a likely irrelevant opinion at that.

It looks like it's come up before: https://github.com/bugsnag/bugsnag-go/issues/10 and the aforementioned https://github.com/bugsnag/bugsnag-go/issues/32

**Comment by kattrali** [comment]
Gotcha, thanks for the follow-ups, @lwc and @Vektah. There are a few things I can do in the near future to make this behavior more clear:

1. Promote the explanation of panic handling in the integration guides, including how to disable it. This should cut down on surprises during initial setup.
2. Update the source documentation of panicwrap.go to more clearly explain what panicwrap does and how (to re-enable the ability to `grep` for "fork" or related terms.
3. Explain more clearly why Bugsnag should be initialized first

Changing the defaults can be part of larger discussion about the next major version though I'm unsure what default would be best.

**Comment by lwc** [comment]
Thanks for your consideration @kattrali, hopefully that list will save future people from the heartache we just experienced 😅 .

My 2c WRT changing the default would be to favour the less surprising option, although I appreciate that provides less cover for apps during their initialisation phase.

Thanks,
Luke

**Comment by kattrali** [comment]
Added some new documentation to clarify the behavior a bit. Thanks again!

* [Initial configuration](http://docs.bugsnag.com/platforms/go/other/#basic-configuration)
* [Reporting unhandled exceptions](http://docs.bugsnag.com/platforms/go/other/#reporting-unhandled-exceptions)
* [default `PanicHandler`](https://github.com/bugsnag/bugsnag-go/blob/57ae5b370355b9fd84333073c6045690af92eed3/panicwrap.go#L10-L14)
