### ISSUE TITLE
Unexpected panic does not appear in the dashboard

### ISSUE THREAD

**Issue by konradreiche** [bugsnag/bugsnag-go#47]
There are a certain scenarios in which an unexpected panic seems to be handled by the Bugsnag Go library and is sent to the backend but does not appear in the dashboard.

I was able to narrow down the scope of those to ones which happen inside a go routine. The confusing part is that bugsnag is clearly handling it as can be seen in the logs:

```
notifying bugsnag: runtime error: invalid memory address or nil pointer dereference
```

What is more, I debugged the behavior and used a custom endpoint to see if there are differences in the messages being sent to the backend. I couldn't see any real difference. Also the fact, that the HTTP POST request is retrieved at the backend should give enough reason to believe that it will also appear in the dashboard.

Only after I started adding
```
defer bugsnag.Recover()
```
at the beginning of each go routine the errors were displayed. This has the unwanted side effect that the Go application doesn't crash.

I did a lot of forth and back testing to make sure this is the only reason, including setting the bugsnag notification to synchronous. Is this behavior known? Can it be explained?

**Comment by kattrali** [comment]
Thanks for the thorough report, @konradreiche. Since you've already retrieved the request which never appears, can you send it to support@bugsnag.com with a link to this issue so we can debug further (and not expose your data)?
