### ISSUE TITLE
Failure modes for async reporting

### ISSUE THREAD

**Issue by EmielM** [bugsnag/bugsnag-go#49]
The code at https://github.com/bugsnag/bugsnag-go/blob/master/notifier.go#L47 worries me a little bit. Although goroutines are pretty cheap in go, I don't think it's idiomatic to just spawn goroutines anywhere you can.

What are the failure modes for this code? If, for instance, my network connection stops working and that results in a lot of errors - but the connection to bugnag also won't work - I would expect a reasonable amount of notifications to be saved in-memory and the remainder to be discarded.

If I read this correctly, this will start spawning goroutines like crazy without any reasonable limit. Wouldn't it be better to push notifications on a channel to a single consumer that tries to push them to bugsnag (but also discards them if the backlog becomes too large)?.

**Comment by kattrali** [comment]
Thank you for the thoughtful report, @EmielM. I think you've outlined the correct approach - a limited amount of caching, and notifying via a channel to efficiently queue reports. Looking into how we can better perform here.
