### ISSUE TITLE
Use of github.com/bugsnag/osext instead of github.com/kardianos/osext

### ISSUE THREAD

**Issue by peterhellberg** [bugsnag/bugsnag-go#54]
## Problem

`github.com/bugsnag/osext` is imported in [panicwrap_test.go](https://github.com/bugsnag/bugsnag-go/blob/b30f231768c71c0d69ca14b217ccced1b9212c45/panicwrap_test.go)

But https://github.com/bugsnag/panicwrap is using `github.com/kardianos/osext`

Is this intentional?

## Expected

That both bugsnag-go and panicwrap would import the same version of osext.

(`github.com/kardianos/osext`)

### Note

I found this issue while trying to use [dep](https://github.com/golang/dep) to vendor bugsnag-go. 

Since bugsnag-go depends on `github.com/bugsnag/osext` then the latest version of `github.com/bugsnag/panicwrap` that can be used is https://github.com/bugsnag/panicwrap/tree/1.1.0 instead of the (i believe) intended master branch.

**Comment by peterhellberg** [comment]
We haven't noticed this issue when using `govendor` since it removes test files (`panicwrap_test.go`)

**Comment by kattrali** [comment]
Thanks for the report, @peterhellberg. This looks like an oversight from bugsnag/panicwrap#3. Updating accordingly.
