### ISSUE TITLE
Proposal: Support for github.com/pkg/errors and TypeName

### ISSUE THREAD

**Issue by proglottis** [bugsnag/bugsnag-go#62]
In https://github.com/bugsnag/bugsnag-go/pull/45 support was added for custom stack frames. I use this to extract the trace from github.com/pkg/errors.

The problem is that since I need a small shim to implement the interface, the error type shown in bugsnag is next to useless (it's almost always the shim). In pkg/errors this could be solved with `errors.Cause(err)` to fetch the original error (and find its type).

One simple solution might be to add another interface check to errors.New and look for `TypeName() string` - which my shim could implement. I'm wondering if there might be a nicer solution?

**Comment by proglottis** [comment]
This got me thinking slightly wider about the bugsnag error package. I think with all those interface checks the connection to this concrete implementation could probably be broken all together, maybe only used as a fallback if all the interface checks fail. Except it's exposed in Event. Probably too large of a change now

**Comment by kattrali** [comment]
Thanks for the report, @proglottis. In the short term, I think support for pkg/errors is a sensible change, specifically to look for `TypeName() string`.

I'm not quite sure what you mean by this though:

> I think with all those interface checks the connection to this concrete implementation could probably be broken all together, maybe only used as a fallback if all the interface checks fail.

**Comment by proglottis** [comment]
Do you mind if I make a PR for this? I'm seem to be struggling to get the tests passing with go 1.9.2 and macos

I mean, if a given error type implements enough of these interfaces, then the actual concrete wrapper probably isn't needed. It's just an implementation detail rather than being part of the API

**Comment by kattrali** [comment]
> Do you mind if I make a PR for this? I'm seem to be struggling to get the tests passing with go 1.9.2 and macos

Definitely! 👍 

> I mean, if a given error type implements enough of these interfaces, then the actual concrete wrapper probably isn't needed. It's just an implementation detail rather than being part of the API

Ah, makes sense now.

**Comment by Gurpartap** [comment]
Bugsnag is missing out on a lot of Go projects because `github.com/pkg/errors` is ubiquitously implemented.

Is this still on the team's todo? Something like this could do: https://github.com/getsentry/raven-go/blob/084a9de9eb0361fbd5ded14b55c84e5493a5d7f6/stacktrace.go#L53-L59

**Comment by cmoad** [comment]
We were able to add support for `github.com/pkg/errors` by implementing the `ErrorsWithCallers` interface. Since this doesn't require any changes to this library, I'm sharing the code that you can use in your own packages.

This gist exposes a `ReportError` function that wraps `bugsnag.Notify` and has the exact same signature. Errors passed in that implement the `stackTracer` interface declared by `github.com/pkg/errors` are wrapped in a private struct that implements `ErrorsWithCallers`. Any improvements are welcomed.

https://gist.github.com/cmoad/90dedff4917a9cca96d151ff1df497f8

**Comment by cmoad** [comment]
Apologies. The gist I provided above was related to the stack, not the type name.

**Comment by kattrali** [comment]
Fixed in [v1.6.0](https://github.com/bugsnag/bugsnag-go/releases/tag/v1.6.0)
