### ISSUE TITLE
"kardianos/osext" is obsolete on go-1.8+

### ISSUE THREAD

**Issue by onlyjob** [bugsnag/bugsnag-go#66]
The following patch allows to remove redundant `github.com/kardianos/osext` dependency:

~~~~
--- a/panicwrap_test.go
+++ b/panicwrap_test.go
@@ -3,9 +3,8 @@
 package bugsnag

 import (
        "github.com/bitly/go-simplejson"
-       "github.com/kardianos/osext"
        "os"
        "os/exec"
        "testing"
        "time"
@@ -60,9 +59,9 @@
        assertSeverityReasonEqual(t, json, "error", "unhandledPanic", true)
 }

 func startPanickingProcess(t *testing.T, variant string) {
-       exePath, err := osext.Executable()
+       exePath, err := os.Executable()
        if err != nil {
                t.Fatal(err)
        }
~~~~

**Comment by fractalwrench** [comment]
Thanks for opening the issue @onlyjob - we still support Go versions below 1.8 so plan on using the `github.com/kardianos/osext` dependency for the foreseeable future.

**Comment by maxp-edcast** [comment]
So uh @fractalwrench how exactly do we use this on go > 1.8 then?

**Comment by maxp-edcast** [comment]
Never mind I just have to `glide get github.com/kardianos/osext` (or ignore it by other means if you don't use glide package manager)

**Comment by kinbiko** [comment]
Closing as we still support Go 1.7 and we cannot yet remove this dependency.

**Comment by onlyjob** [comment]
Please reopen. Eventually this will have to be done. It will be silly to report this again.

You are not going to support Golang-1.7 forever.
